# Generated by Django 5.1.1 on 2024-09-23 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
