# Generated by Django 5.1.1 on 2024-10-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
    ]
