# Generated by Django 5.1.2 on 2024-10-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0013_alter_transaction_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_description',
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_pin',
        ),
        migrations.RemoveField(
            model_name='account',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='account',
            name='initial_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_joint_account',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_overdrawn',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='account',
            name='overdraft_limit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='routing_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checkings', 'Checkings'), ('savings', 'Savings'), ('money market', 'Money Market'), ('certificates of deposits', 'Certificates of Deposits'), ('brokerage', 'Brokerage'), ('retirement', 'Retirement'), ('business checkings', 'Business Checkings'), ('business savings', 'Business Savings'), ('health savings', 'Health Savings'), ('education savings', 'Education Savings'), ('joint', 'Joint'), ('trust', 'Trust'), ('estodial', 'Estodial')], default='checkings', max_length=36),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='RecurringPayment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
