# Generated by Django 5.1.1 on 2024-10-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0017_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
