# Generated by Django 5.1.1 on 2024-10-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0018_transaction_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='slug',
        ),
    ]
