# Generated by Django 5.1.1 on 2024-10-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0020_transaction_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('authorized', 'Authorized'), ('settled', 'Settled'), ('disputed', 'Disputed'), ('expired', 'Expired'), ('processing', 'Processing'), ('scheduled', 'Scheduled'), ('partially_completed', 'Partially Completed'), ('awaiting_approval', 'Awaiting Approval'), ('declined', 'Declined'), ('chargeback', 'Chargeback'), ('queued', 'Queued'), ('voided', 'Voided'), ('manual_review', 'Manual Review'), ('reattempt', 'Reattempt')], default='pending', max_length=21),
        ),
    ]
