# Generated by Django 5.1.1 on 2024-10-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0023_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
