# Generated by Django 5.1.2 on 2024-10-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0026_alter_category_name_alter_category_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
