# Generated by Django 5.1.2 on 2024-10-26 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0028_alter_budget_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_type', models.CharField(choices=[('Stocks', 'Equities'), ('Bonds', 'Fixed Income'), ('Real Estate', 'Real Estate'), ('Mutual Funds', 'Mutual Funds'), ('ETFs', 'Exchange-Traded Funds'), ('Commodities', 'Commodities'), ('Cryptocurrencies', 'Cryptocurrencies'), ('Derivatives', 'Derivatives'), ('Private Equity', 'Private Equity and Venture Capital'), ('Hedge Funds', 'Hedge Funds'), ('Collectibles', 'Collectibles'), ('Savings', 'Savings')], default='Stocks', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_invested', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
