# Generated by Django 5.1.2 on 2024-10-28 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0029_investment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='date_invested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_type', models.CharField(choices=[('personal', 'Personal'), ('home', 'Home'), ('student', 'Student'), ('auto', 'Auto'), ('business', 'Business'), ('payday', 'Payday'), ('credit builder', 'Credit Builder'), ('agricultural', 'Agricultural'), ('other', 'Other')], default='personal', max_length=60)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('application stage', 'Application State'), ('funding stage', 'Funding Stage'), ('repayment stage', 'Repayment Stage'), ('deliquency stage', 'Deliquency Stage'), ('final stage', 'Final Stage')], default='application stage', max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
