# Generated by Django 5.1.2 on 2024-10-29 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0030_alter_investment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('application stage', 'Application Stage'), ('funding stage', 'Funding Stage'), ('repayment stage', 'Repayment Stage'), ('deliquency stage', 'Deliquency Stage'), ('final stage', 'Final Stage')], default='application stage', max_length=60),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True)),
                ('status', models.CharField(choices=[('creation and processing stage', 'Creation and Processing Stage'), ('billing and nofitified stage', 'Billing and Nofitified Stage'), ('payment stage', 'Payment Stage'), ('late and collection stage', 'Late and Collection Stage'), ('adjustment and finalization stage', 'Adjustment and Finaliztion Stage'), ('closed', 'Closed')], default='creation and processing stage', max_length=36)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jzj.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
