# Generated by Django 5.1.2 on 2024-10-31 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0034_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('tax_year', models.IntegerField(blank=True, null=True)),
                ('income_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('tax_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('tax_owed', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('attatchments', models.FileField(blank=True, null=True, upload_to='')),
                ('tax_filing_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED_FILING_JOINTLY', 'Married Filing Jointly'), ('MARRIED_FILING_SEPARATELY', 'Married Filing Separately'), ('HEAD_OF_HOUSEHOLD', 'Head of Household'), ('QUALIFYING_WIDOWER', 'Qualifying Widow(er) with Dependent Child')], default='SINGLE', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_APPROVAL', 'Pending Approval'), ('FILED', 'Filed'), ('PROCESSING', 'Processing'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AMENDED', 'Amended'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=80)),
                ('tax_form', models.CharField(choices=[('FORM_1040', '1040 - U.S. Individual Income Tax Return'), ('FORM_1040A', '1040A - U.S. Individual Income Tax Return (Short Form)'), ('FORM_1040EZ', '1040EZ - U.S. Individual Income Tax Return (Simplified)'), ('FORM_1065', '1065 - U.S. Return of Partnership Income'), ('FORM_1120', '1120 - U.S. Corporation Income Tax Return'), ('FORM_1120S', '1120S - U.S. Income Tax Return for an S Corporation'), ('FORM_1099', '1099 - Miscellaneous Income'), ('FORM_W2', 'W2 - Wage and Tax Statement'), ('FORM_990', '990 - Return of Organization Exempt from Income Tax'), ('FORM_706', '706 - United States Estate (and Generation-Skipping Transfer) Tax Return')], default='FORM_1040', max_length=90)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='CO', max_length=2)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
