# Generated by Django 5.1.2 on 2024-10-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0035_taxrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('BANK', 'Bank'), ('CREDIT_UNION', 'Credit Union'), ('INSURANCE_COMPANY', 'Insurance Company'), ('INVESTMENT_FIRM', 'Investment Firm'), ('MUTUAL_FUND', 'Mutual Fund'), ('BROKERAGE', 'Brokerage'), ('OTHER', 'Other')], default='BANK', max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
