# Generated by Django 5.1.2 on 2024-10-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0036_financialinstitution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinstitution',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
