# Generated by Django 5.1.2 on 2024-10-31 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0037_alter_financialinstitution_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialinstitution',
            name='institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
