# Generated by Django 5.1.2 on 2024-10-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0041_remove_bill_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
