# Generated by Django 5.1.2 on 2024-10-31 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0042_alter_account_last_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='account',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taxrecord',
            old_name='account',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
