# Generated by Django 5.1.2 on 2024-11-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jzj', '0044_checkoutsessionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
